# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9653c743bf12d7154d384f9e361a6dcfea77698a702ac1e7d53e5e2b8faee4ae6af923ea14150cc0484abb4724eeef70e7fd9b614773a3e7d120474735d45a89
  PAGSEGURO_EMAIL: erickvictor@gmail.com
  PAGSEGURO_TOKEN: 50F0C4FDA2774176A5A0ED050334D8DA

test:
  secret_key_base: 52bcc63b8ba3d62b7b620224905de932544be1512fc93da6ad7bc06cbabacca7a49ce9cd0e44e8e561c0e84b6f064acc24a50ac758a4b441ed46cc3da1ed0627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
